namespace GateServer.Packs.Protocols
{
    internal class GameProtocols
    {
        public static readonly Dictionary<ushort, BaseProtocol> Instance;

        static GameProtocols()
        {
            Instance = new Dictionary<ushort, BaseProtocol>()
            {
                /*
                // LoginService
                {0x03F0,    new BaseProtocol() { Size=38,       Name="UserChangeRolePacket", Description="更改角色名称" } },
                {0x03EF,    new BaseProtocol() { Size=6,        Name="TestNetworkSpeedPacket", Description="测试网关网速" } },
                {0x03EE,    new BaseProtocol() { Size=6,        Name="UserEnterPacket", Description="进入游戏" } },
                {0x03ED,    new BaseProtocol() { Size=6,        Name="UserBackRolePacket", Description="找回冻结的角色" } },
                {0x03EC,    new BaseProtocol() { Size=6,        Name="UserDelectRolePacket", Description="用户删除角色" } },
                {0x03EB,    new BaseProtocol() { Size=6,        Name="UserFreezeRolePacket", Description="冻结角色" } },
                {0x03EA,    new BaseProtocol() { Size=40,       Name="UserCreateRolePacket", Description="创建角色" } },
                {0x03E9,    new BaseProtocol() { Size=162,      Name="UserLoginPacket", Description="客户登录" } },
                */
                {0x0284,    new BaseProtocol() { Size=0,        Name="UnknownC644", Description="UnknownC1" } },
                {0x0282,    new BaseProtocol() { Size=4,        Name="UnknownC642", Description="UnknownC1" } },
                {0x0274,    new BaseProtocol() { Size=10,       Name="跨服武道排名", Description="跨服武道排名" } },
                {0x0270,    new BaseProtocol() { Size=6,        Name="查看演武排名", Description="查看演武排名" } },
                {0x026A,    new BaseProtocol() { Size=9,        Name="上架平台商品", Description="上架平台商品" } },
                {0x0268,    new BaseProtocol() { Size=6,        Name="InquireAboutSpecifiedProductPacket", Description="InquireAboutSpecifiedProductPacket" } },
                {0x0267,    new BaseProtocol() { Size=6,        Name="查询平台商品", Description="查询平台商品" } },
                {0x0266,    new BaseProtocol() { Size=3,        Name="LoginConsignmentPlatformPacket", Description="LoginConsignmentPlatformPacket" } },
                {0x0265,    new BaseProtocol() { Size=4,        Name="购买玛法特权", Description="购买玛法特权" } },
                {0x0262,    new BaseProtocol() { Size=9,        Name="SendMessageCodeVerificationPacket", Description="SendMessageCodeVerificationPacket" } },
                {0x025C,    new BaseProtocol() { Size=10,       Name="查询排名榜单", Description="查询排名榜单" } },
                {0x025A,    new BaseProtocol() { Size=2,        Name="查询出售信息", Description="查询出售信息" } },
                {0x0258,    new BaseProtocol() { Size=42,       Name="购买珍宝商品", Description="购买珍宝商品" } },
                {0x0257,    new BaseProtocol() { Size=6,        Name="RequestTreasureDataPacket", Description="RequestTreasureDataPacket" } },
                {0x0256,    new BaseProtocol() { Size=2,        Name="打开角色背包", Description="打开角色背包" } },
                {0x024C,    new BaseProtocol() { Size=38,       Name="玩家屏蔽对象", Description="玩家屏蔽对象" } },
                {0x0248,    new BaseProtocol() { Size=28,       Name="申请行会Hostility", Description="申请行会Hostility" } },
                {0x0247,    new BaseProtocol() { Size=7,        Name="处理解敌申请", Description="处理解敌申请" } },
                {0x0246,    new BaseProtocol() { Size=6,        Name="申请解除Hostility", Description="申请解除Hostility" } },
                {0x0245,    new BaseProtocol() { Size=6,        Name="开启行会活动", Description="开启行会活动" } },
                {0x0244,    new BaseProtocol() { Size=2,        Name="QueryGuildAchievementsPacket", Description="QueryGuildAchievementsPacket" } },
                {0x0243,    new BaseProtocol() { Size=27,       Name="StartGuildWarPacket", Description="StartGuildWarPacket" } },
                {0x023E,    new BaseProtocol() { Size=2,        Name="更多GuildEvents", Description="更多GuildEvents" } },
                {0x023D,    new BaseProtocol() { Size=8,        Name="GuildWarehouseMovePacket", Description="GuildWarehouseMovePacket" } },
                {0x023C,    new BaseProtocol() { Size=5,        Name="更改存储权限", Description="更改存储权限" } },
                {0x023B,    new BaseProtocol() { Size=6,        Name="申请解除结盟", Description="申请解除结盟" } },
                {0x023A,    new BaseProtocol() { Size=7,        Name="处理结盟申请", Description="处理结盟申请" } },
                {0x0239,    new BaseProtocol() { Size=2,        Name="查看结盟申请", Description="查看结盟申请" } },
                {0x0238,    new BaseProtocol() { Size=29,       Name="申请行会外交", Description="申请行会外交" } },
                {0x0237,    new BaseProtocol() { Size=6,        Name="TransferPresidentPositionPacket", Description="TransferPresidentPositionPacket" } },
                {0x0236,    new BaseProtocol() { Size=6,        Name="ExpelMembersPacket", Description="ExpelMembersPacket" } },
                {0x0235,    new BaseProtocol() { Size=7,        Name="变更会员职位", Description="变更会员职位" } },
                {0x0234,    new BaseProtocol() { Size=7,        Name="设置行会禁言", Description="设置行会禁言" } },
                {0x0233,    new BaseProtocol() { Size=0,        Name="更改行会宣言", Description="更改行会宣言" } },
                {0x0232,    new BaseProtocol() { Size=0,        Name="更改行会公告", Description="更改行会公告" } },
                {0x0231,    new BaseProtocol() { Size=2,        Name="申请解散行会", Description="申请解散行会" } },
                {0x0230,    new BaseProtocol() { Size=7,        Name="处理入会邀请", Description="处理入会邀请" } },
                {0x022F,    new BaseProtocol() { Size=34,       Name="InviteToJoinGuildPacket", Description="InviteToJoinGuildPacket" } },
                {0x022E,    new BaseProtocol() { Size=7,        Name="处理入会申请", Description="处理入会申请" } },
                {0x022D,    new BaseProtocol() { Size=2,        Name="查看申请列表", Description="查看申请列表" } },
                {0x022C,    new BaseProtocol() { Size=31,       Name="申请加入行会", Description="申请加入行会" } },
                {0x022B,    new BaseProtocol() { Size=31,       Name="FindCorrespondingGuildPacket", Description="FindCorrespondingGuildPacket" } },
                {0x022A,    new BaseProtocol() { Size=2,        Name="更多行会信息", Description="更多行会信息" } },
                {0x0229,    new BaseProtocol() { Size=7,        Name="查看行会列表", Description="查看行会列表" } },
                {0x0228,    new BaseProtocol() { Size=10,       Name="查询GuildName", Description="查询GuildName" } },
                {0x0227,    new BaseProtocol() { Size=14,       Name="提取邮件附件", Description="提取邮件附件" } },
                {0x0226,    new BaseProtocol() { Size=14,       Name="删除指定邮件", Description="删除指定邮件" } },
                {0x0225,    new BaseProtocol() { Size=14,       Name="查看邮件内容", Description="查看邮件内容" } },
                {0x0224,    new BaseProtocol() { Size=2,        Name="QueryMailboxContentPacket", Description="QueryMailboxContentPacket" } },
                {0x0223,    new BaseProtocol() { Size=0,        Name="申请发送邮件", Description="申请发送邮件" } },
                {0x0222,    new BaseProtocol() { Size=2,        Name="提交出师申请", Description="提交出师申请" } },
                {0x0221,    new BaseProtocol() { Size=0,        Name="CongratsToApprenticeForUpgradePacket", Description="CongratsToApprenticeForUpgradePacket(已弃用)" } },
                {0x0220,    new BaseProtocol() { Size=2,        Name="查询师门成员", Description="查询师门成员(师徒通用)" } },
                {0x021F,    new BaseProtocol() { Size=6,        Name="AppForExpulsionPacket", Description="AppForExpulsionPacket" } },
                {0x021E,    new BaseProtocol() { Size=2,        Name="离开师门申请", Description="离开师门申请" } },
                {0x021C,    new BaseProtocol() { Size=6,        Name="RejectionApprenticeshipAppPacket", Description="RejectionApprenticeshipAppPacket" } },
                {0x021B,    new BaseProtocol() { Size=6,        Name="同意收徒申请", Description="同意收徒申请" } },
                {0x021A,    new BaseProtocol() { Size=7,        Name="玩家申请收徒", Description="玩家申请收徒" } },
                {0x0218,    new BaseProtocol() { Size=6,        Name="RefusedApplyApprenticeshipPacket", Description="RefusedApplyApprenticeshipPacket" } },
                {0x0217,    new BaseProtocol() { Size=6,        Name="同意拜师申请", Description="同意拜师申请" } },
                {0x0216,    new BaseProtocol() { Size=6,        Name="玩家申请拜师", Description="玩家申请拜师" } },
                {0x0215,    new BaseProtocol() { Size=2,        Name="查询收徒名册", Description="查询收徒名册(已弃用, 不推送)" } },
                {0x0214,    new BaseProtocol() { Size=2,        Name="查询拜师名册", Description="查询拜师名册(已弃用, 不推送)" } },
                {0x0212,    new BaseProtocol() { Size=2,        Name="查询地图路线", Description="查询地图路线" } },
                {0x0211,    new BaseProtocol() { Size=0,        Name="SendSocialMessagePacket", Description="SendChatMessagePacket(公会/队伍/私人)" } },
                {0x0210,    new BaseProtocol() { Size=6,        Name="玩家删除仇人", Description="删除仇人" } },
                {0x020F,    new BaseProtocol() { Size=6,        Name="玩家添加仇人", Description="添加仇人" } },
                {0x020E,    new BaseProtocol() { Size=0,        Name="SendFriendChatPacket", Description="好友聊天" } },
                {0x020D,    new BaseProtocol() { Size=40,       Name="上传社交信息", Description="上传社交信息(已屏蔽)" } },
                {0x020C,    new BaseProtocol() { Size=7,        Name="MobileFriendsGroupPacket", Description="MobileFriendsGroupPacket(已屏蔽)" } },
                {0x020B,    new BaseProtocol() { Size=6,        Name="取消好友关注", Description="取消好友关注" } },
                {0x020A,    new BaseProtocol() { Size=38,       Name="AddFriendsToFollowPacket", Description="AddFriendsToFollowPacket" } },
                {0x0209,    new BaseProtocol() { Size=7,        Name="申请创建队伍", Description="申请创建队伍" } },
                {0x0208,    new BaseProtocol() { Size=6,        Name="查询队伍信息", Description="查询队伍信息" } },
                {0x0207,    new BaseProtocol() { Size=44,       Name="申请更改队伍", Description="申请更改队伍" } },
                {0x0205,    new BaseProtocol() { Size=6,        Name="申请离开队伍", Description="申请离开队伍" } },
                {0x0204,    new BaseProtocol() { Size=6,        Name="SendTeamRequestPacket", Description="SendTeamRequestPacket" } },
                {0x0203,    new BaseProtocol() { Size=10,       Name="RequestCharacterDataPacket", Description="RequestCharacterDataPacket" } },
                {0x0110,    new BaseProtocol() { Size=2,        Name="UnknownC272", Description="UnknownC272" } },
                {0x010F,    new BaseProtocol() { Size=2,        Name="PlayerEnterScenePacket", Description="Received on player connects (ver. 1.0.3.68 / 185578)" } },
                {0x010B,    new BaseProtocol() { Size=142,      Name="UnknownC267", Description="UnknownC267" } },
                {0x010A,    new BaseProtocol() { Size=11,       Name="UnknownC266", Description="Unknown266" } },
                {0x0109,    new BaseProtocol() { Size=11,       Name="UnknownC265", Description="UnknownC4" } },
                {0x0108,    new BaseProtocol() { Size=22,       Name="UnknownC264", Description="UnknownC4" } },
                {0x00FE,    new BaseProtocol() { Size=6,        Name="购买每周特惠", Description="购买每周特惠" } },
                {0x00FC,    new BaseProtocol() { Size=0,        Name="UnknownC252", Description="UnknownC252" } },
                {0x00FB,    new BaseProtocol() { Size=3,        Name="ReservedPacketZeroThreePacket", Description="不知道干嘛的" } },
                {0x00F8,    new BaseProtocol() { Size=6,        Name="EnterMartialArtsBatllefieldPacket", Description="EnterMartialArtsBatllefieldPacket" } },
                {0x00F7,    new BaseProtocol() { Size=2,        Name="刷新演武挑战", Description="刷新演武挑战" } },
                {0x00F6,    new BaseProtocol() { Size=10,       Name="开始战场演武", Description="开始战场演武" } },
                {0x00F1,    new BaseProtocol() { Size=4,        Name="玩家喝修复油", Description="玩家喝修复油" } },
                {0x00ED,    new BaseProtocol() { Size=8,        Name="回应组队请求", Description="回应组队请求" } },
                {0x00EB,    new BaseProtocol() { Size=6,        Name="QuestTeleportPacket", Description="QuestTeleportPacket" } },
                {0x00E9,    new BaseProtocol() { Size=2,        Name="查询奖励找回", Description="查询奖励找回" } },
                {0x00E7,    new BaseProtocol() { Size=6,        Name="RequestSoulStoneDataPacket", Description="RequestSoulStoneDataPacket" } },
                {0x00E2,    new BaseProtocol() { Size=4,        Name="UpgradeAwakeningSkillPacket", Description="UpgradeAwakeningSkillPacket" } },
                {0x00E1,    new BaseProtocol() { Size=3,        Name="ToggleAwakeningExpPacket", Description="ToggleAwekeningExpPacket" } },
                {0x00E0,    new BaseProtocol() { Size=6,        Name="RequestDragonguardDataPacket", Description="RequestDragonguardDataPacket" } },
                {0x00DB,    new BaseProtocol() { Size=5,        Name="AddMountSkillPacket", Description="AddMountSkillPacket" } },
                {0x00DA,    new BaseProtocol() { Size=3,        Name="GetCurrentMountPacket", Description="GetCurrentMountPacket" } },
                {0x00D9,    new BaseProtocol() { Size=3,        Name="BookMarfaPrivilegesPacket", Description="BookMarfaPrivilegesPacket" } },
                {0x00D8,    new BaseProtocol() { Size=4,        Name="领取特权礼包", Description="领取特权礼包" } },
                {0x00D4,    new BaseProtocol() { Size=2,        Name="SyncedWantedListPacket", Description="SyncedWantedListPacket" } },
                {0x00D3,    new BaseProtocol() { Size=50,       Name="PublishWantedListPacket", Description="PublishWantedListPacket" } },
                {0x00BF,    new BaseProtocol() { Size=2,        Name="玩家每日签到", Description="玩家每日签到" } },
                {0x00BE,    new BaseProtocol() { Size=3,        Name="更改PetMode", Description="更改PetMode" } },
                {0x00BC,    new BaseProtocol() { Size=2,        Name="查询问卷调查", Description="查询问卷调查" } },
                {0x00BB,    new BaseProtocol() { Size=9,        Name="ReservedPacketZeroTwoPacket", Description="不知道干嘛的, 离开进入安全区触发" } },
                {0x00B7,    new BaseProtocol() { Size=2,        Name="玩家退出登录", Description="玩家退出登录" } },
                {0x00B5,    new BaseProtocol() { Size=6,        Name="玩家解除屏蔽", Description="玩家解除屏蔽" } },
                {0x00B2,    new BaseProtocol() { Size=3,        Name="QueryGuildBattleHistoryPacket", Description="QueryGuildBattleHistoryPacket" } },
                {0x00B1,    new BaseProtocol() { Size=2,        Name="申请离开行会", Description="申请离开行会" } },
                {0x00B0,    new BaseProtocol() { Size=0,        Name="DistributeGuildBenefitsPacket", Description="DistributeGuildBenefitsPacket" } },
                {0x00A6,    new BaseProtocol() { Size=8,        Name="GuildWarehouseTransferOutPacket", Description="GuildWarehouseTransferOutPacket" } },
                {0x00A5,    new BaseProtocol() { Size=8,        Name="GuildWarehouseTransferPacket", Description="GuildWarehouseTransferPacket" } },
                {0x00A4,    new BaseProtocol() { Size=8,        Name="GuildWarehouseRefreshPacket", Description="GuildWarehouseRefreshPacket" } },
                {0x00A3,    new BaseProtocol() { Size=6,        Name="DonateGuildFundsPacket", Description="DonateGuildFundsPacket" } },
                {0x00A1,    new BaseProtocol() { Size=0,        Name="CreateGuildPacket", Description="申请创建行会" } },
                {0x00A0,    new BaseProtocol() { Size=2,        Name="查询师门奖励", Description="查询师门奖励(师徒通用)" } },
                {0x009E,    new BaseProtocol() { Size=3,        Name="更改收徒推送", Description="更改收徒推送" } },
                {0x009D,    new BaseProtocol() { Size=6,        Name="AcceptRewardPacket", Description="AcceptRewardPacket" } },
                {0x009C,    new BaseProtocol() { Size=6,        Name="玩家比较成就", Description="玩家比较成就" } },
                {0x009B,    new BaseProtocol() { Size=6,        Name="UnknownC155", Description="UnknownC1" } },
                {0x009A,    new BaseProtocol() { Size=2,        Name="玩家结束交易", Description="玩家结束交易" } },
                {0x0099,    new BaseProtocol() { Size=2,        Name="玩家解锁交易", Description="玩家解锁交易" } },
                {0x0098,    new BaseProtocol() { Size=2,        Name="玩家确认交易", Description="玩家确认交易" } },
                {0x0097,    new BaseProtocol() { Size=2,        Name="玩家锁定交易", Description="玩家锁定交易" } },
                {0x0096,    new BaseProtocol() { Size=6,        Name="玩家放入物品", Description="玩家放入物品" } },
                {0x0095,    new BaseProtocol() { Size=6,        Name="玩家放入金币", Description="玩家放入金币" } },
                {0x0094,    new BaseProtocol() { Size=6,        Name="玩家同意交易", Description="玩家同意交易" } },
                {0x0093,    new BaseProtocol() { Size=6,        Name="玩家申请交易", Description="玩家申请交易" } },
                {0x0092,    new BaseProtocol() { Size=2,        Name="玩家卸下称号", Description="玩家卸下称号" } },
                {0x0091,    new BaseProtocol() { Size=3,        Name="玩家装配称号", Description="玩家装配称号" } },
                {0x008C,    new BaseProtocol() { Size=2,        Name="查询附近队伍", Description="查询附近队伍" } },
                {0x0089,    new BaseProtocol() { Size=0,        Name="上传游戏设置", Description="上传游戏设置" } },
                {0x0087,    new BaseProtocol() { Size=28,       Name="CreateNewFriendGroupPacket", Description="CreateNewFriendGroupPacket(已屏蔽)" } },
                {0x0086,    new BaseProtocol() { Size=3,        Name="ToggleMapRoutePacket", Description="ToggleMapRoutePacket" } },
                {0x0083,    new BaseProtocol() { Size=0,        Name="SendChatMessagePacket", Description="SendChatMessagePacket(附近|广播|传音)" } },
                {0x0077,    new BaseProtocol() { Size=6,        Name="继续Npcc对话", Description="提交选项继续NPC对话" } },
                {0x0075,    new BaseProtocol() { Size=6,        Name="开始Npcc对话", Description="点击Npc开始与之对话" } },
                {0x0074,    new BaseProtocol() { Size=6,        Name="OpenChestPacket", Description="OpenChestPacket" } },
                {0x0073,    new BaseProtocol() { Size=6,        Name="玩家放弃任务", Description="玩家放弃任务" } },
                {0x0072,    new BaseProtocol() { Size=10,       Name="PlayerCompleteQuestPacket", Description="玩家完成任务" } },
                {0x0071,    new BaseProtocol() { Size=14,       Name="ClickNpcDialogPacket", Description="ClickNpcDialogPacket" } },
                {0x0070,    new BaseProtocol() { Size=17,       Name="购买摊位物品", Description="购买摊位物品" } },
                {0x006F,    new BaseProtocol() { Size=6,        Name="打开角色摊位", Description="打开角色摊位" } },
                {0x006E,    new BaseProtocol() { Size=3,        Name="更改摊位外观", Description="更改摊位外观" } },
                {0x006D,    new BaseProtocol() { Size=35,       Name="更改摊位名字", Description="更改摊位名字" } },
                {0x006C,    new BaseProtocol() { Size=3,        Name="取回摊位物品", Description="取回摊位物品" } },
                {0x006B,    new BaseProtocol() { Size=11,       Name="PutItemsInBoothPacket", Description="PutItemsInBoothPacket" } },
                {0x006A,    new BaseProtocol() { Size=2,        Name="玩家收起摊位", Description="玩家收起摊位" } },
                {0x0069,    new BaseProtocol() { Size=2,        Name="玩家开始摆摊", Description="玩家开始摆摊" } },
                {0x0068,    new BaseProtocol() { Size=2,        Name="玩家重整摊位", Description="玩家重整摊位" } },
                {0x0067,    new BaseProtocol() { Size=2,        Name="玩家准备摆摊", Description="玩家准备摆摊" } },
                {0x0062,    new BaseProtocol() { Size=3,        Name="RequestLockStoragePacket", Description="RequestLockStoragePacket" } },
                {0x0061,    new BaseProtocol() { Size=5,        Name="LockItemPacket", Description="LockItemPacket" } },
                {0x005E,    new BaseProtocol() { Size=2,        Name="随身特修全部", Description="随身特修全部" } },
                {0x005D,    new BaseProtocol() { Size=8,        Name="随身修理单件", Description="随身修理单件" } },
                {0x0057,    new BaseProtocol() { Size=6,        Name="CharacterSynthesisItemPacket", Description="CharacterSynthesisItemPacket" } },
                {0x0056,    new BaseProtocol() { Size=5,        Name="CharacterBreakdownItemsPacket", Description="CharacterBreakdownItemsPacket" } },
                {0x004F,    new BaseProtocol() { Size=14,       Name="升级武器普通", Description="升级武器普通" } },
                {0x004E,    new BaseProtocol() { Size=11,       Name="AbandonInscriptionReplacementPacket", Description="AbandonInscriptionReplacementPacket" } },
                {0x004D,    new BaseProtocol() { Size=4,        Name="ReplaceLowLevelInscriptionsPacket", Description="ReplaceLowLevelInscriptionsPacket" } },
                {0x004C,    new BaseProtocol() { Size=8,        Name="ReplaceInscriptionRefinementPacket", Description="ReplaceInscriptionRefinementPacket" } },
                {0x004B,    new BaseProtocol() { Size=5,        Name="ToggleDoubleInscriptionBitPacket", Description="ToggleDoubleInscriptionBitPacket" } },
                {0x004A,    new BaseProtocol() { Size=5,        Name="UnlockDoubleInscriptionSlotPacket", Description="UnlockDoubleInscriptionSlotPacket" } },
                {0x0049,    new BaseProtocol() { Size=4,        Name="ReplaceAdvancedInscriptionPacket", Description="ReplaceAdvancedInscriptionPacket" } },
                {0x0048,    new BaseProtocol() { Size=8,        Name="高级铭文洗练", Description="高级铭文洗练" } },
                {0x0047,    new BaseProtocol() { Size=6,        Name="传承武器铭文", Description="传承武器铭文" } },
                {0x0046,    new BaseProtocol() { Size=8,        Name="OrdinaryInscriptionRefinementPacket", Description="OrdinaryInscriptionRefinementPacket" } },
                {0x0045,    new BaseProtocol() { Size=5,        Name="玩家拆除灵石", Description="玩家拆除灵石" } },
                {0x0044,    new BaseProtocol() { Size=7,        Name="玩家镶嵌灵石", Description="玩家镶嵌灵石" } },
                {0x0041,    new BaseProtocol() { Size=6,        Name="RequestStoreDataPacket", Description="RequestStoreDataPacket" } },
                {0x003A,    new BaseProtocol() { Size=3,        Name="CharacterOrganizerBackpackPacket", Description="CharacterOrganizerBackpackPacket" } },
                {0x0039,    new BaseProtocol() { Size=4,        Name="玩家扩展背包", Description="玩家扩展背包" } },
                {0x0037,    new BaseProtocol() { Size=4,        Name="商店特修单件", Description="商店特修单件" } },
                {0x0036,    new BaseProtocol() { Size=2,        Name="商店修理全部", Description="商店修理全部" } },
                {0x0035,    new BaseProtocol() { Size=4,        Name="商店修理单件", Description="商店修理单件" } },
                {0x0034,    new BaseProtocol() { Size=3,        Name="CharacterRepurchageItemsPacket", Description="CharacterRepurchageItemsPacket" } },
                {0x0033,    new BaseProtocol() { Size=2,        Name="查询回购列表", Description="SyncRepoListPacket" } },
                {0x0032,    new BaseProtocol() { Size=6,        Name="CharacterSellItemsPacket", Description="CharacterSellItemsPacket" } },
                {0x0031,    new BaseProtocol() { Size=12,       Name="CharacterPurchageItemsPacket", Description="CharacterPurchageItemsPacket" } },
                {0x0030,    new BaseProtocol() { Size=7,        Name="CharacterPickupItemsPacket", Description="CharacterPickupItemsPacket" } },
                {0x002F,    new BaseProtocol() { Size=6,        Name="CharacterDropsItemsPacket", Description="CharacterDropsItemsPacket" } },
                {0x002E,    new BaseProtocol() { Size=8,        Name="CharacterSplitItemsPacket", Description="CharacterSplitItemsPacket" } },
                {0x002D,    new BaseProtocol() { Size=4,        Name="CharacterUseItemsPacket", Description="CharacterUseItemsPacket" } },
                {0x002C,    new BaseProtocol() { Size=6,        Name="CharacterTransferItemPacket", Description="物品转移/交换/合并/更换装备" } },
                {0x0028,    new BaseProtocol() { Size=4,        Name="BattleStanceSwitchPacket", Description="BattleStanceSwitchPacket" } },
                {0x0027,    new BaseProtocol() { Size=5,        Name="CharacterEquipmentSkillsPacket", Description="装备技能" } },
                {0x0026,    new BaseProtocol() { Size=3,        Name="ToggleAttackMode", Description="ToggleAttackMode" } },
                {0x0022,    new BaseProtocol() { Size=16,       Name="CharacterReleaseSkillsPacket", Description="释放技能" } },
                {0x0021,    new BaseProtocol() { Size=4,        Name="CharacterSwitchSkillsPacket", Description="CharacterSwitchSkillsPacket" } },
                {0x0020,    new BaseProtocol() { Size=15,       Name="ReservedPacketZeroOnePacket", Description="不知道干嘛的, 离开进入安全区触发" } },
                {0x001F,    new BaseProtocol() { Size=6,        Name="CharacterSelectionTargetPacket", Description="CharacterSelectionTargetPacket" } },
                {0x0019,    new BaseProtocol() { Size=2,        Name="跳过剧情动画", Description="跳过剧情动画" } },
                {0x0018,    new BaseProtocol() { Size=3,        Name="客户请求复活", Description="玩家请求复活" } },
                {0x0017,    new BaseProtocol() { Size=6,        Name="客户网速测试", Description="帧同步, 请求Ping" } },
                {0x0016,    new BaseProtocol() { Size=6,        Name="客户进入法阵", Description="进入传送门触发" } },
                {0x0015,    new BaseProtocol() { Size=6,        Name="同步角色战力", Description="同步角色战力" } },
                {0x0014,    new BaseProtocol() { Size=22,       Name="查看玩家装备", Description="查看玩家装备, 右键头像查看资料时触发" } },
                {0x0013,    new BaseProtocol() { Size=10,       Name="RequestObjectDataPacket", Description="同步对象外观" } },
                {0x0012,    new BaseProtocol() { Size=6,        Name="客户角色走动", Description="角色走动" } },
                {0x0011,    new BaseProtocol() { Size=6,        Name="客户角色跑动", Description="角色跑动" } },
                {0x0010,    new BaseProtocol() { Size=8,        Name="客户角色转动", Description="角色转动" } },
                {0x000F,    new BaseProtocol() { Size=2,        Name="客户碰触法阵", Description="到达传送门/摆摊点" } },
                {0x000E,    new BaseProtocol() { Size=10,       Name="上传角色位置", Description="上传角色位置" } },
                {0x000C,    new BaseProtocol() { Size=10,       Name="场景加载完成", Description="场景加载完成" } },
                {0x000B,    new BaseProtocol() { Size=2,        Name="ExitCurrentCopyPacket", Description="ExitCurrentCopyPacket" } },
                {0x000A,    new BaseProtocol() { Size=6,        Name="客户更换角色", Description="更换角色" } },
            };
        }
    }
}
